---
-
  name: "Valdivia's Five Letters to the King of Spain, 1545-1552"
  shortname: "letters"
  galleries:
    -
      name: "The first Valdivia Letter, dated 4 September 1545"
      shortname: "First"
      path: "L1"
      filename: "first_letter.yaml"
      label-prefix: "L1"
      images_per_row: 3
    -
      name: "The second letter, dated 15 June 1548"
      shortname: "Second"
      path: "L2"
      filename: "second_letter.yaml"
      label-prefix: "L2"
      images_per_row: 3
    -
      name: "The third letter, dated 15 October 1550"
      shortname: "Third"
      path: "L3"
      filename: "third_letter.yaml"
      label-prefix: "L3"
      images_per_row: 3
    -
      name: "The fourth letter, dated 25 September 1551"
      shortname: "Fourth"
      path: "L4"
      filename: "fourth_letter.yaml"
      label-prefix: "L4"
      images_per_row: 3
    -
      name: "The fifth letter, dated 26 October 1552"
      shortname: "Fifth"
      path: "L5"
      filename: "fifth_letter.yaml"
      label-prefix: "L5"
      images_per_row: 3
-
  name: "The Distribution of Atahuallpa's Ransom"
  shortname: "ransom"
  galleries:
    -
      name: "The Distribution of Atahuallpa's Ransom"
      shortname: "Ransom"
      path: "R"
      filename: "ransom.yaml"
      label-prefix: "R"
      images_per_row: 3
-
  name: "William H. Prescott's evaluation of the historian, Pedro Pizarro"
  shortname: "pizzaro"
  galleries:
    -
      name: "William H. Prescott's evaluation of the historian, Pedro Pizarro"
      shortname: "Pizzaro"
      path: "P"
      filename: "pizzaro.yaml"
      label-prefix: "P"
      images_per_row: 3
-
  name: "William H. Prescott's evaluation of the historian, Cieza de Leon"
  shortname: "leon"
  galleries:
    -
      name: "William H. Prescott's evaluation of the historian, Cieza de Leon"
      shortname: "Leon"
      path: "L"
      filename: "leon.yaml"
      label-prefix: "L"
      images_per_row: 3
