---
-
  name: "Valdivia's Five Letters to the King of Spain, 1545-1552"
  shortname: "letters"
  galleries:
    -
      name: "The first Valdivia Letter, dated 4 September 1545"
      shortname: "First"
      path: "L1"
      filename: "first_letter.yaml"
      label-prefix: "L1"
      images_per_row: 3
    -
      name: "The second letter, dated 15 June 1548"
      shortname: "Second"
      path: "L2"
      filename: "second_letter.yaml"
      label-prefix: "L2"
      images_per_row: 3
    -
      name: "The third letter, dated 15 October 1550"
      shortname: "Third"
      path: "L3"
      filename: "third_letter.yaml"
      label-prefix: "L3"
      images_per_row: 3
    -
      name: "The fourth letter, dated 25 September 1551"
      shortname: "Fourth"
      path: "L4"
      filename: "fourth_letter.yaml"
      label-prefix: "L4"
      images_per_row: 3
    -
      name: "The fifth letter, dated 26 October 1552"
      shortname: "Fifth"
      path: "L5"
      filename: "fifth_letter.yaml"
      label-prefix: "L5"
      images_per_row: 3
-
  name: "The Distribution of Atahuallpa's Ransom"
  shortname: "ransom"
  galleries:
    -
      name: "The Distribution of Atahuallpa's Ransom"
      shortname: "Ransom"
      path: "R"
      filename: "ransom.yaml"
      label-prefix: "R"
      images_per_row: 3
-
  name: "Description of Pachacamac by E. George Squier"
  shortname: "pachacamac"
  galleries:
    -
      name: "Description of Pachacamac by E. George Squier"
      shortname: "Pachacamac"
      path: "pachacamac"
      filename: "pachacamac.yaml"
      label-prefix: "P"
      images_per_row: 3
-
  name: "Cusco, the Sacred City Description by E. George Squier"
  shortname: "cusco"
  galleries:
    -
      name: "Cusco, the Sacred City Description by E. George Squier"
      shortname: "Cusco"
      path: "C"
      filename: "cusco.yaml"
      label-prefix: "C"
      images_per_row: 3
-
  name: "Fortress Sacsayhuaman by Victor W. Von Hagen"
  shortname: "sacsayhuaman"
  galleries:
    -
      name: "Fortress Sacsayhuaman by Victor W. Von Hagen"
      shortname: "Sacsayhuaman"
      path: "S"
      filename: "sacsayhuaman.yaml"
      label-prefix: "S"
      images_per_row: 3
-
  name: "Lima, the City of Kings by E. George Squier"
  shortname: "lima"
  galleries:
    -
      name: "Lima, the City of Kings by E. George Squier"
      shortname: "Lima"
      path: "lima"
      filename: "lima.yaml"
      label-prefix: "L"
      images_per_row: 3
-
  name: "Tiwanaku: Remnant of an Ancient Civilization by E. George Squier"
  shortname: "tiwanaku"
  galleries:
    -
      name: "Tiwanaku: Remnant of an Ancient Civilization by E. George Squier"
      shortname: "Tiwanaku"
      path: "tiwanaku"
      filename: "tiwanaku.yaml"
      label-prefix: "T"
      images_per_row: 3
-
  name: "Citadel Ollantaytambo by E. George Squier"
  shortname: "ollantaytambo"
  galleries:
    -
      name: "Citadel Ollantaytambo by E. George Squier"
      shortname: "Ollantaytambo"
      path: "O"
      filename: "ollantaytambo.yaml"
      label-prefix: "O"
      images_per_row: 3
-
  name: "William H. Prescott's evaluation of the historian, Pedro Pizarro"
  shortname: "pizzaro"
  galleries:
    -
      name: "William H. Prescott's evaluation of the historian, Pedro Pizarro"
      shortname: "Pizzaro"
      path: "P"
      filename: "pizzaro.yaml"
      label-prefix: "P"
      images_per_row: 3
-
  name: "William H. Prescott's evaluation of the historian, Cieza de Leon"
  shortname: "leon"
  galleries:
    -
      name: "William H. Prescott's evaluation of the historian, Cieza de Leon"
      shortname: "Leon"
      path: "L"
      filename: "leon.yaml"
      label-prefix: "L"
      images_per_row: 3
-
  name: "William H. Prescott's evaluation of the historian, Garcilasso de la Vega"
  shortname: "vega_prescott"
  galleries:
    -
      name: "William H. Prescott's evaluation of the historian, Garcilasso de la Vega"
      shortname: "Vega"
      path: "vega_prescott"
      filename: "vega_prescott.yaml"
      label-prefix: "V"
      images_per_row: 3
-
  name: "William H. Prescott's Portrait of Marshal Diego de Almagro"
  shortname: "almagro_prescott"
  galleries:
    -
      name: "William H. Prescott's Portrait of Marshal Diego de Almagro"
      shortname: "Almagro"
      path: "almagro_prescott"
      filename: "almagro_prescott.yaml"
      label-prefix: "A"
      images_per_row: 3
-
  name: "William H. Prescott's portrait of Hernando Pizarro"
  shortname: "hernando_prescott"
  galleries:
    -
      name: "William H. Prescott's portrait of Hernando Pizarro"
      shortname: "Hernando"
      path: "hernando_prescott"
      filename: "hernando_prescott.yaml"
      label-prefix: "H"
      images_per_row: 3
-
  name: "William H. Prescott's Description of the Assassination of Francisco Pizarro"
  shortname: "assassination"
  galleries:
    -
      name: "William H. Prescott's Description of the Assassination of Francisco Pizarro"
      shortname: "Assassination"
      path: "assassination"
      filename: "assassination.yaml"
      label-prefix: "A"
      images_per_row: 3
-
  name: "William H. Prescott's Portrait of Marquess Francisco Pizarro"
  shortname: "francisco_prescott"
  galleries:
    -
      name: "William H. Prescott's Portrait of Marquess Francisco Pizarro"
      shortname: "Francisco"
      path: "francisco_prescott"
      filename: "francisco_prescott.yaml"
      label-prefix: "F"
      images_per_row: 3
-
  name: "Agustín de Zárate's Description of Gonzalo Pizarro's Expedition to locate the Land of Cinnamon and to find the Land of El Dorado"
  shortname: "zarate"
  galleries:
    -
      name: "Agustín de Zárate's Description of Gonzalo Pizarro's Expedition to locate the Land of Cinnamon and to find the Land of El Dorado"
      shortname: "El Dorado"
      path: "zarate"
      filename: "zarate.yaml"
      label-prefix: "Z"
      images_per_row: 3
-
  name: "John Hemming's Description of Gonzalo Pizarro's Expedition to locate the Lands of Cinnamon and of El Dorado"
  shortname: "hemming"
  galleries:
    -
      name: "John Hemming's Description of Gonzalo Pizarro's Expedition to locate the Lands of Cinnamon and of El Dorado"
      shortname: "El Dorado"
      path: "hemming"
      filename: "hemming.yaml"
      label-prefix: "H"
      images_per_row: 3
