---
-
  name: "Edward Whymper's description of Quito from \"Travels Amongst the Great Andes of the Equator.\""
  shortname: "quito"
  galleries:
    -
      name: "Edward Whymper's description of Quito from \"Travels Amongst the Great Andes of the Equator.\""
      shortname: "Quito"
      path: "quito"
      filename: "quito.yaml"
      label-prefix: "Q"
      images_per_row: 3
-
  name: "Tiwanaku: Remnant of an Ancient Civilization by E. George Squier"
  shortname: "tiwanaku"
  galleries:
    -
      name: "Tiwanaku: Remnant of an Ancient Civilization by E. George Squier"
      shortname: "Tiwanaku"
      path: "tiwanaku"
      filename: "tiwanaku.yaml"
      label-prefix: "T"
      images_per_row: 3
-
  name: "Pichincha Peak, as described by Edward Whymper in, \"Travels Amongst the Great Andes of the Equator.\""
  shortname: "pichincha"
  galleries:
    -
      name: "Pichincha Peak, as described by Edward Whymper in, \"Travels Amongst the Great Andes of the Equator.\""
      shortname: "Pichincha"
      path: "pichincha"
      filename: "pichincha.yaml"
      label-prefix: "P"
      images_per_row: 3
-
  name: "Edward Whymper's first ascent of Cayambe in \"Travels Amongst the Great Andes of the Equator.\""
  shortname: "cayambe"
  galleries:
    -
      name: "Edward Whymper's first ascent of Cayambe in \"Travels Amongst the Great Andes of the Equator.\""
      shortname: "Cayambe"
      path: "cayambe"
      filename: "cayambe.yaml"
      label-prefix: "C"
      images_per_row: 3
-
  name: "The first ascent of Cotopaxi by Edward Whymper from, \"Travels Amongst the Great Andes of the Equator.\""
  shortname: "cotopaxi"
  galleries:
    -
      name: "The first ascent of Cotopaxi by Edward Whymper from, \"Travels Amongst the Great Andes of the Equator.\""
      shortname: "Cotopaxi"
      path: "cotopaxi"
      filename: "cotopaxi.yaml"
      label-prefix: "C"
      images_per_row: 3
-
  name: "Edward Whymper's description of the first ascent of Chimborazo."
  shortname: "chimborazo"
  galleries:
    -
      name: "Edward Whymper's description of the first ascent of Chimborazo."
      shortname: "Chimborazo"
      path: "chimborazo"
      filename: "chimborazo.yaml"
      label-prefix: "C"
      images_per_row: 3
-
  name: "The first ascent of Illimani from \"Climbing and Exploration in the Bolivian Andes\" by Sir Martin Conway."
  shortname: "illimani"
  galleries:
    -
      name: "The first ascent of Illimani from \"Climbing and Exploration in the Bolivian Andes\" by Sir Martin Conway."
      shortname: "Illimani"
      path: "illimani"
      filename: "illimani.yaml"
      label-prefix: "I"
      images_per_row: 3
-
  name: "The first ascent of Aconcagua, from \"The Highest Andes\" by E. A. Fitz Gerald."
  shortname: "aconcagua"
  galleries:
    -
      name: "The first ascent of Aconcagua, from \"The Highest Andes\" by E. A. Fitz Gerald."
      shortname: "Aconcagua"
      path: "aconcagua"
      filename: "aconcagua.yaml"
      label-prefix: "A"
      images_per_row: 3
-
  name: "South American Handbook (1990) Description of Quito."
  shortname: "handbook"
  galleries:
    -
      name: "South American Handbook (1990) Description of Quito."
      shortname: "Handbook"
      path: "handbook"
      filename: "handbook.yaml"
      label-prefix: "Q"
      images_per_row: 3
-
  name: "Harry A. Franck's description of Pasto, Colombia from \"Vagabonding Down the Andes.\""
  shortname: "pasto"
  galleries:
    -
      name: "Harry A. Franck's description of Pasto, Colombia from \"Vagabonding Down the Andes.\""
      shortname: "Pasto"
      path: "pasto"
      filename: "pasto.yaml"
      label-prefix: "P"
      images_per_row: 3
-
  name: "Harry A. Franck's description of the llama from \"Vagabonding Down the Andes.\""
  shortname: "llama"
  galleries:
    -
      name: "Harry A. Franck's description of the llama from \"Vagabonding Down the Andes.\""
      shortname: "Llama"
      path: "llama"
      filename: "llama.yaml"
      label-prefix: "L"
      images_per_row: 3
-
  name: "Machu Picchu Description by Harry A. Franck."
  shortname: "machu"
  galleries:
    -
      name: "Machu Picchu Description by Harry A. Franck."
      shortname: "Machu Picchu"
      path: "machu"
      filename: "machu.yaml"
      label-prefix: "M"
      images_per_row: 3
-
  name: "Description of La Paz by Harry A, Franck."
  shortname: "lapaz"
  galleries:
    -
      name: "Description of La Paz by Harry A, Franck."
      shortname: "La Paz"
      path: "lapaz"
      filename: "lapaz.yaml"
      label-prefix: "L"
      images_per_row: 3
-
  name: "A Description of Cusco by Harry A. Franck."
  shortname: "cusco_franck"
  galleries:
    -
      name: "A Description of Cusco by Harry A. Franck."
      shortname: "Cusco"
      path: "cusco_franck"
      filename: "cusco_franck.yaml"
      label-prefix: "C"
      images_per_row: 3
-
  name: "Edward Whymper's Scientific Work to Determine Altitude."
  shortname: "altitude"
  galleries:
    -
      name: "Edward Whymper's Scientific Work to Determine Altitude."
      shortname: "Altitude"
      path: "altitude"
      filename: "altitude.yaml"
      label-prefix: "A"
      images_per_row: 3
